In [ ]:


from sklearn import svm
import numpy as np
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.model_selection import cross_validate
import os as os
from sklearn.model_selection import cross_val_score
from sklearn import metrics
from sklearn import linear_model


: 

In [18]:


###########################
# LOADING TRAINING DATA
###########################
os.chdir('C:/Users/Mrida/Documents/Python/who-is-more-influential-master/Original Dataset')
trainfile = open('train.csv')
for line in trainfile:
    header = line.rstrip().split(',')
    break

y_train = []
X_train_A = []
X_train_B = []

for line in trainfile:
    splitted = line.rstrip().split(',')
    label = int(splitted[0])
    A_features = [float(item) for item in splitted[1:12]]
    B_features = [float(item) for item in splitted[12:]]
    y_train.append(label)
    X_train_A.append(A_features)
    X_train_B.append(B_features)
trainfile.close()

y_train = np.array(y_train)
X_train_A = np.array(X_train_A)
X_train_B = np.array(X_train_B)
print(X_train_A[0:10])
print(y_train[0:10])

[[2.28000000e+02 3.02000000e+02 3.00000000e+00 5.83979388e-01
  1.00503359e-01 1.00503359e-01 1.00503359e-01 3.62150068e-01
  2.00000000e+00 1.66500000e+02 1.13550000e+04]
 [2.15910000e+04 1.17900000e+03 2.28000000e+02 9.04565058e+01
  2.57982918e+01 5.70932865e+00 1.11115882e+00 5.17662002e+00
  3.69000000e+02 1.84429708e+01 1.33036605e+03]
 [7.31000000e+03 1.21500000e+03 1.01000000e+02 2.55036445e+01
  9.55634744e+00 5.36151928e+00 5.91205607e-01 3.58971842e+00
  9.50000000e+01 6.89278351e+01 5.99989691e+03]
 [2.00000000e+01 7.00000000e+00 2.00000000e+00 7.69082373e+00
  2.77305641e-01 1.33150798e+00 1.00503359e-01 2.83062680e+00
  6.00000000e+00 2.00000000e+00 9.61666667e+01]
 [4.55890000e+04 8.62000000e+02 2.64100000e+03 1.48854279e+02
  3.69988839e+01 2.78817679e+01 3.33349180e+00 2.38612817e+01
  5.51000000e+02 1.27404293e+02 2.83384794e+03]
 [2.85735000e+05 2.76251000e+05 3.41700000e+03 1.93275815e+01
  7.29201558e+00 1.00503359e-01 1.00503359e-01 1.00503359e-01
  6.00000000e+01

In [19]:
def transform_features(x):
    return np.log(1+x)
    #x = (x - np.mean(x,axis = 0))/np.std(x,axis = 0) 
    #return x

In [21]:
X_train = transform_features(X_train_A) - transform_features(X_train_B)
model=svm.SVC(probability=True);

C = 1.0  # SVM regularization parameter
 
model = svm.SVC(kernel='rbf', C=C, probability=True).fit(X_train, y_train)  
p_train = model.predict_proba(X_train)
p_train = p_train[:,1:2]
precision, recall, thresholds=precision_recall_curve(y_train,p_train[:,0])
 
print("******************Support vector Machine Accuracy******************")
 
print('SVM Accuracy:',roc_auc_score(y_train,p_train[:,0]))
print("Top Five Prediction Results")
print(p_train[0:10])

C:\Users\Mrida\anaconda3\envs\tp\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


******************Support vector Machine Accuracy******************
SVM Accuracy: 0.9289610460388085
Top Five Prediction Results
[[0.17530098]
 [0.16676802]
 [0.53671888]
 [0.17526201]
 [0.84481085]
 [0.39194637]
 [0.15558249]
 [0.39859321]
 [0.82701269]
 [0.22801191]]


In [22]:
model2=linear_model.LogisticRegression(fit_intercept=False).fit(X_train, y_train)

# Logistic regression # 
p_train1 = model2.predict_proba(X_train) 
p_train1 = p_train1[:,1:2]
precision, recall, thresholds=precision_recall_curve(y_train,p_train1[:,0])
 
print("******************Logistic Regression Accuracy******************")
 
print('Logistic Regression Accuracy:',roc_auc_score(y_train,p_train1[:,0]))
print("Top Five Prediction Results")
print(p_train1[0:10])

******************Logistic Regression Accuracy******************
Logistic Regression Accuracy: 0.8630826810670553
Top Five Prediction Results
[[0.07308298]
 [0.34484905]
 [0.67473849]
 [0.02235788]
 [0.79521737]
 [0.61478659]
 [0.29782152]
 [0.35229926]
 [0.59178693]
 [0.42840826]]


C:\Users\Mrida\anaconda3\envs\tp\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [23]:

###########################
# READING TEST DATA
###########################

testfile = open('C:\\Users\\Mrida\\Documents\\Python\\who-is-more-influential-master\\Original Dataset\\test.csv')
#ignore the test header
for line in testfile:
    break

X_test_A = []
X_test_B = []
for line in testfile:
    splitted = line.rstrip().split(',')
    A_features = [float(item) for item in splitted[0:11]]
    B_features = [float(item) for item in splitted[11:]]
    X_test_A.append(A_features)
    X_test_B.append(B_features)
testfile.close()

X_test_A = np.array(X_test_A)
X_test_B = np.array(X_test_B)

# transform features in the same way as for training to ensure consistency
X_test = transform_features(X_test_A) - transform_features(X_test_B)

# compute probabilistic predictions
p_test = model.predict_proba(X_test)
#only need the probability of the 1 class
p_test = p_test[:,1:2]
print("Top Five Prediction Results")
print(p_test[0:10])


Top Five Prediction Results
[[0.19571401]
 [0.10218223]
 [0.20105596]
 [0.23407099]
 [0.72194551]
 [0.17988734]
 [0.78903648]
 [0.78504206]
 [0.19336028]
 [0.77682522]]


In [24]:

###########################
# WRITING SUBMISSION FILE
###########################
predfile = open('predictions.csv','w+')
predfile.write('Id,Choice\n')
i=1;
for line in p_test:
    x=str(i)+','+str(line[0])
    predfile.write(x)
    predfile.write('\n')
    i=i+1

predfile.close()
print(" Most influence Users data is Stored in CSV File")

 Most influence Users data is Stored in CSV File
